---
name: "КиноПоиск"
guid: "a0ad3c8a-0e15-4c2f-8f5a-9c7b6d4e3f2a"
version: "1.0.0.0"
targetAbi: "10.9.0.0"
framework: "net8.0"
owner: "Your Name"
overview: "Метаданные фильмов и сериалов с сайта КиноПоиск"
description: >
  Плагин для загрузки метаданных с сайта kinopoisk.ru.
  Поддерживает фильмы, сериалы, актёров.
  Загружает рейтинги, описания, постеры и актёрский состав.
category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.Kinopoisk.dll"
changelog: >
  1.0.0.0:
    - Начальный релиз
    - Поддержка фильмов и сериалов
    - Загрузка постеров и задников
    - Информация об актёрах и режиссёрах
    - Кеширование запросов
    - Rate limiting для предотвращения блокировки
